config:
  registries:
    - name: ECR
      api_url: https://437327607644.dkr.ecr.eu-central-1.amazonaws.com
      prefix: 437327607644.dkr.ecr.eu-central-1.amazonaws.com
      ping: yes
      default: true
      insecure: false
      credentials: ext:/scripts/ecr-login.sh    
      credsexpire: 12h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      aws ecr --region "eu-central-1" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d