config:
  registries:
    - name: ECR
      api_url: https://437327607644.dkr.ecr.eu-central-1.amazonaws.com
      prefix: 437327607644.dkr.ecr.eu-central-1.amazonaws.com
      ping: yes
      insecure: no
      credentials: ext:/scripts/login.sh
      credsexpire: 6h

authScripts:
  enabled: true
  scripts:
      login.sh: |
        #!/bin/sh
        aws ecr --region "eu-central-1" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
