replicaCount: 1
image:
  repository: 437327607644.dkr.ecr.eu-central-1.amazonaws.com/argo-test
<<<<<<< HEAD
  tag: "1.1.0"
=======
  tag: "1.0.5"
>>>>>>> 6ec8163 (manuell)
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30050
